### ISSUE TITLE
[Bug] Chrome is not defined

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#123]
**Describe the bug**
```
webpack 5.65.0 compiled with 3 warnings in 6749 ms
🕷   Starting crawling http://localhost:64341/
Error: Uncaught [ReferenceError: chrome is not defined]
    at reportException (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at Object.check (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:92:23)
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request._callback (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/request/request.js:185:22) ReferenceError: chrome is not defined
    at Object.7430 (http://localhost:64341/static/js/main.5e399683.js:1:9179)
    at M (http://localhost:64341/static/js/main.5e399683.js:13:32115)
    at http://localhost:64341/static/js/main.5e399683.js:13:34191
    at Function.M.O (http://localhost:64341/static/js/main.5e399683.js:13:32532)
    at http://localhost:64341/static/js/main.5e399683.js:13:34206
    at http://localhost:64341/static/js/main.5e399683.js:13:34213
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at processJavaScript (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
```

**Root cause**
react-snapshot is using jsdom. (https://github.com/geelen/react-snapshot/pull/44#issuecomment-341292537)

**Comment by gaupoit** [comment]
It also crashes on Firefox or Safari
![Screen Shot 2022-08-16 at 07 58 37](https://user-images.githubusercontent.com/4486806/184766773-407ea159-a1ac-45a2-9d62-aea85f24fa04.png)
